"""
PDF Engine Module - Handles PDF creation for CourseSmith AI.
Uses ReportLab's Platypus engine for complex layout.
"""

from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image,
    PageBreak,
)
from reportlab.lib.colors import HexColor
import os


class PDFBuilder:
    """Class to handle PDF document creation with cover page and chapters."""

    def __init__(self, filename):
        """
        Initialize the PDF builder with document settings.

        Args:
            filename: The output PDF filename.
        """
        self.filename = filename
        self.doc = SimpleDocTemplate(
            filename,
            pagesize=letter,
            rightMargin=0.75 * inch,
            leftMargin=0.75 * inch,
            topMargin=0.75 * inch,
            bottomMargin=0.75 * inch,
        )
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()

    def _setup_custom_styles(self):
        """Setup custom paragraph styles for the document."""
        # Cover title style
        self.styles.add(
            ParagraphStyle(
                name="CoverTitle",
                parent=self.styles["Heading1"],
                fontName="Helvetica-Bold",
                fontSize=36,
                leading=42,
                alignment=TA_CENTER,
                spaceAfter=20,
                textColor=HexColor("#1a1a2e"),
            )
        )

        # Cover subtitle style
        self.styles.add(
            ParagraphStyle(
                name="CoverSubtitle",
                parent=self.styles["Normal"],
                fontName="Helvetica",
                fontSize=18,
                leading=22,
                alignment=TA_CENTER,
                spaceAfter=30,
                textColor=HexColor("#4a4a6a"),
            )
        )

        # Chapter header style
        self.styles.add(
            ParagraphStyle(
                name="ChapterHeader",
                parent=self.styles["Heading1"],
                fontName="Helvetica-Bold",
                fontSize=24,
                leading=30,
                spaceBefore=20,
                spaceAfter=15,
                textColor=HexColor("#1a1a2e"),
            )
        )

        # Body text style (custom version)
        self.styles.add(
            ParagraphStyle(
                name="CustomBodyText",
                parent=self.styles["Normal"],
                fontName="Helvetica",
                fontSize=12,
                leading=18,
                alignment=TA_JUSTIFY,
                spaceBefore=6,
                spaceAfter=12,
            )
        )

    def _create_cover_page(self, title, audience, cover_image_path, story):
        """
        Create the cover page with image, title, and subtitle.

        Args:
            title: The course/book title.
            audience: The target audience description.
            cover_image_path: Path to the cover image file.
            story: The story list to append elements to.
        """
        # Add spacer at top
        story.append(Spacer(1, 0.5 * inch))

        # Add cover image if it exists and is valid
        if cover_image_path and os.path.exists(cover_image_path):
            # Validate file extension for security
            valid_extensions = ('.png', '.jpg', '.jpeg', '.gif', '.bmp')
            if cover_image_path.lower().endswith(valid_extensions):
                # Calculate image dimensions to fit page width
                page_width = letter[0] - (1.5 * inch)  # Account for margins
                img = Image(cover_image_path)

                # Scale image to fit width while maintaining aspect ratio
                aspect = img.imageHeight / float(img.imageWidth)
                img_width = min(page_width, 5 * inch)
                img_height = img_width * aspect

                # Limit height if too tall
                max_height = 4 * inch
                if img_height > max_height:
                    img_height = max_height
                    img_width = img_height / aspect

                img.drawWidth = img_width
                img.drawHeight = img_height
                img.hAlign = "CENTER"
                story.append(img)
                story.append(Spacer(1, 0.5 * inch))

        # Add title
        story.append(Paragraph(title, self.styles["CoverTitle"]))

        # Add subtitle with audience
        subtitle = f"A Comprehensive Guide for {audience}"
        story.append(Paragraph(subtitle, self.styles["CoverSubtitle"]))

        # Add generated by note
        story.append(Spacer(1, 1 * inch))
        generated_note = "Generated by CourseSmith AI"
        story.append(Paragraph(generated_note, self.styles["CoverSubtitle"]))

        # Page break after cover
        story.append(PageBreak())

    def _add_chapters(self, chapters_data, story):
        """
        Add chapter content to the document.

        Args:
            chapters_data: List of dicts with 'title' and 'content' keys.
            story: The story list to append elements to.
        """
        for i, chapter in enumerate(chapters_data, 1):
            # Chapter header
            chapter_title = f"Chapter {i}: {chapter['title']}"
            story.append(Paragraph(chapter_title, self.styles["ChapterHeader"]))

            # Chapter content - split into paragraphs
            content = chapter.get("content", "")
            paragraphs = content.split("\n\n")

            for para in paragraphs:
                para = para.strip()
                if para:
                    # Handle text wrapping automatically with Paragraph
                    story.append(Paragraph(para, self.styles["CustomBodyText"]))

            # Add space between chapters
            story.append(Spacer(1, 0.3 * inch))

    def build_pdf(self, title, audience, cover_image_path, chapters_data):
        """
        Build the complete PDF document.

        Args:
            title: The course/book title.
            audience: The target audience description.
            cover_image_path: Path to the cover image file.
            chapters_data: List of dicts with 'title' and 'content' keys.

        Returns:
            str: The filename of the generated PDF.
        """
        story = []

        # Create cover page
        self._create_cover_page(title, audience, cover_image_path, story)

        # Add chapters
        self._add_chapters(chapters_data, story)

        # Build the document
        self.doc.build(story)

        return self.filename
